CREATE TABLE Servers (
	ServerId BIGINT NOT NULL,
	ChannelId BIGINT NULL,
	Schedule INT NULL,
	CONSTRAINT Servers_PK PRIMARY KEY (ServerId)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE Mods (
	ModId BIGINT NOT NULL,
	ModName varchar(100) NOT NULL,
	LastUpdate BIGINT NOT NULL,
    PreviewUrl VARCHAR(2083) NULL,
	CONSTRAINT Mods_PK PRIMARY KEY (ModId)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE Subscriptions (
	ServerId BIGINT NOT NULL,
	ModId BIGINT NOT NULL,
	LastUpdate BIGINT NULL,
	CONSTRAINT Subscriptions_PK PRIMARY KEY (ServerId,ModId),
	CONSTRAINT Subscriptions_FK FOREIGN KEY (ModId) REFERENCES Mods(ModId) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Subscriptions_FK_1 FOREIGN KEY (ServerId) REFERENCES Servers(ServerId) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
