CREATE TABLE Servers (
	ServerId BIGINT NOT NULL,
	ChannelId BIGINT NULL,
	Schedule INT NULL,
	LastUpdate BIGINT NULL,
	CONSTRAINT Servers_PK PRIMARY KEY (ServerId)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE Items (
	ItemId BIGINT NOT NULL,
	ItemName varchar(100) NOT NULL,
	LastUpdate BIGINT NOT NULL,
    PreviewUrl VARCHAR(2083) NULL,
	CONSTRAINT Items_PK PRIMARY KEY (ItemId)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE Subscriptions (
	ServerId BIGINT NOT NULL,
	ItemId BIGINT NOT NULL,
	LastUpdate BIGINT NULL,
	Note varchar(500) NULL,
	CONSTRAINT Subscriptions_PK PRIMARY KEY (ServerId,ItemId),
	CONSTRAINT Subscriptions_FK FOREIGN KEY (ItemId) REFERENCES Items(ItemId) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Subscriptions_FK_1 FOREIGN KEY (ServerId) REFERENCES Servers(ServerId) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
